name:                snaplet-redis
version:             0.1.6.1
synopsis:            Redis support for Snap Framework
description:
  >-
    This package provides a snaplet which exposes interface to Redis
    in-memory key-value storage as implemented by Hedis library.
    Inline documentation contains usage examples.

github:       dzhus/snaplet-redis
license:      BSD3
author:       Dmitry Dzhus
maintainer:   dima@dzhus.org
category:     Web, Snap

extra-source-files:
  - CHANGELOG.md
  - README.md

flags:
  Example:
    description: Build example
    manual: False
    default: False

library:
  ghc-options: -Wall -Wcompat
  source-dirs: src
  dependencies:
    - base < 5
    - bytestring
    - cereal
    - clientsession
    - configurator
    - lens < 5
    - hedis
    - mtl
    - snap
    - snap-core
    - text
    - time
    - unordered-containers

executables:
  Example:
    when:
      - condition: (!flag(Example))
        buildable: false
    main: Site.hs
    source-dirs:
      - example
    dependencies:
      - base
      - bytestring
      - lens < 5
      - hedis
      - mtl
      - snap
      - snap-core
      - snap-server
      - snaplet-redis
      - text
