name:                snaplet-redis
version:             0.1.5
synopsis:            Redis support for Snap Framework
description:
  >-
    This package provides a snaplet which exposes interface to Redis
    in-memory key-value storage as implemented by Hedis library.
    Inline documentation contains usage examples.

github:       dzhus/snaplet-redis
license:      BSD3
author:       Dmitry Dzhus
maintainer:   dima@dzhus.org
category:     Web, Snap

extra-source-files:
  - CHANGELOG.md

flags:
  Example:
    description: Build example
    manual: False
    default: False

library:
  ghc-options: -Wall
  source-dirs: src
  dependencies:
    - base < 5
    - bytestring
    - cereal
    - clientsession
    - configurator
    - lens
    - hedis
    - mtl
    - network
    - snap
    - snap-core
    - transformers
    - text
    - time
    - unordered-containers

executables:
  Example:
    when:
      - condition: flag(Example)
        then:
          buildable: True
        else:
          buildable: False
    main: Site.hs
    source-dirs:
      - example
    dependencies:
      - base
      - aeson
      - bytestring
      - lens
      - hedis
      - heist
      - monad-control
      - mtl
      - snap
      - snap-core
      - snap-server
      - snaplet-redis
      - text
      - time
      - xmlhtml
