resolver: lts-17.9
pvp-bounds: upper
extra-deps:
- snap-1.1.3.1
- aeson-1.4.7.1
- heist-1.1.0.1
- map-syntax-0.3
- pwstore-fast-2.4.4
- xmlhtml-0.2.5.2
- th-abstraction-0.3.2.0
- bifunctors-5.5.7
- free-5.1.3
- invariant-0.5.3
- semigroupoids-5.3.3